# Generated by Django 4.1.7 on 2023-04-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='NOWe',
        ),
    ]
