# Generated by Django 4.1.7 on 2023-04-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_rename_user_nowe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NOWe',
            new_name='Benutzer',
        ),
    ]
