# Generated by Django 4.1.7 on 2023-04-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_rename_nowe_benutzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='benutzer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='benutzer',
            name='firma',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='benutzer',
            name='message',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='benutzer',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='benutzer',
            name='nachname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='benutzer',
            name='vorname',
            field=models.CharField(max_length=50),
        ),
    ]
