# Generated by Django 4.1.7 on 2023-04-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_benutzer_email_benutzer_firma_benutzer_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benutzer',
            new_name='Nutzer',
        ),
    ]
