# Generated by Django 4.1.7 on 2023-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_rename_benutzer_nutzer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewNutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('tel', models.CharField(default='', max_length=20)),
                ('firma', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Nutzer',
        ),
    ]
